version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      adguard:
        patterns:
          - '@adguard/*'
    labels:
      - "PR: Dependencies :nut_and_bolt:"
