name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: Install dependencies
        run: npm ci       
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run unit tests
        run: npm run test.unit
      - name: Run e2e tests
        run: npm run test.e2e
      - name: Run linting
        run: npm run lint

  release:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: jdx/mise-action@v2
      - name: Install dependencies
        run: npm ci
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.ADBLOCKERBOT_APP_ID }}
          private-key: ${{ secrets.ADBLOCKERBOT_PRIVATE_KEY }}
      - name: Create Release PR or Publish to npm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          if [ -n "$(git log --oneline -1 | grep -o 'skip-release')" ]; then
            echo "Skipping release due to skip-release commit message"
            exit 0
          fi
          npm run release
