name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v1
        with:
          version: latest
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Install Playwright
        run: bun x playwright install --with-deps
      - name: Run unit tests
        run: bun run test.unit
      - name: Run e2e tests
        run: bun run test.e2e
      - name: Run linting
        run: bun run lint

  release:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: jdx/mise-action@v1
        with:
          version: latest
      - name: Install dependencies
        run: bun install
      - name: Create Release PR or Publish to npm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          if [ -n "$(git log --oneline -1 | grep -o 'skip-release')" ]; then
            echo "Skipping release due to skip-release commit message"
            exit 0
          fi
          bun run release 