name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Read parameters
        id: read
        run: |
          echo "tool_versions="$(cat ./.tool_versions)"" >> "$GITHUB_OUTPUT"

      - uses: jdx/mise-action@v2
        with:
          install: true
          cache: true
          tool_versions: ${{ steps.read.outputs.tool_versions }}

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
