name: Remove Dependabot Version Labels

on:
  pull_request:
    types: [labeled, opened]
    branches:
      - main

jobs:
  remove_labels:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Remove version labels
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: patch,minor,major
